### PR TITLE
fix: order status check before order line item update

### PR DESCRIPTION
**Pull request by bplaquevent**
I think the Mollie integration shouldn't block OROCommerce order line updates.
So I submit you a pull request allowing to ignore Mollie order line update if the corresponding order has not a status allowing to do so.

### CODE REVIEW

**Comment by DamjanLogeecom** [comment]
Hello bplaquevent,

Please note that we will review your pull request and we will notify you once we have more information to provide.

Kind regards.

**Comment by DamjanLogeecom** [comment]
Hello bplaquevent,

This is just a quick note to inform you that our team has already started working on resolving your issue.

If you have any further questions or concerns, please let us know.

Best regards,

Logeecom team

**Comment by tanjalog** [comment]
Hey @bplaquevent,

Please note that we are still reviewing your pull request and we will update you soon regarding it.

Best regards.

**Comment by tanjalog** [comment]
Hey @bplaquevent,

First, thank you one more time for your pull request.

After analyzing we concluded that we can not accept it because we have to keep two systems in a consistent state, so if the order is updated in the shop, even if the Mollie API order line update request failed, would lead to a difference between order data in the shop and in Mollie.

Also, since Mollie handles payment for an order, it does not make sense to make a change on any order that is then rejected by the payment system and that change still goes through in the shop system.

We apricate your sugestion.

Best regards

**Pull request closed without merging**
